### ISSUE TITLE
Netgauze-flow-pkt build fails due to IANA Information Elements Registry update.

### ISSUE THREAD

**Issue by PhilVince96** [NetGauze/NetGauze#89]
<img width="2082" alt="Screenshot 2024-10-08 at 11 39 13" src="https://github.com/user-attachments/assets/47494376-016c-4d1a-aa2f-273ceb5db194">

Yesterday, on the seventh of October 2024,
there have been updates to the [IANA Information Elements](https://www.iana.org/assignments/ipfix/ipfix.xhtml) related to IP Flow Information Export (IPFIX). Two key changes include fixes for outdated elements in the IANA IPFIX registry and new Information Elements for handling extended TCP options and IPv6 extension headers. The updates aim to correct issues like incomplete coverage of IPv6 extension headers and improvements to the IEs for more accurate and consistent reporting of network flow data.
These changes address discrepancies and limitations in previous specifications. For example, the deprecation of the ipv6ExtensionHeaders and tcpOptions IEs, originally defined in RFC 5102, is one of the key updates. The new elements provide better handling of TCP and IPv6 flows, as well as improvements in how flow data is collected and exported.
The abstract data type 'unsigned256' was introduced (see [here](https://datatracker.ietf.org/doc/draft-ietf-opsawg-ipfix-tcpo-v6eh/)), which leads to an error in the netgauze-flow-pkt crate, which pulls from the IANA registry and does not know this new 'unsigned256' abstract data type.

**Comment by PhilVince96** [comment]
<img width="2082" alt="Screenshot 2024-10-08 at 11 52 49" src="https://github.com/user-attachments/assets/6b80fa8b-aafe-4a30-a934-5c703934aaff">
Same when running the ipfix.rs example with cargo run --example ipfix on the newest commit on main.

**Comment by PhilVince96** [comment]
Is there a way of making the crate work, even if it currently does not support the changed IE?

**Comment by ahassany** [comment]
Fixed in PR #100.
